
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 03 14:41:21 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 42;
  public static final int CHAR = 47;
  public static final int CONST = 3;
  public static final int GRT = 25;
  public static final int GRTEQ = 26;
  public static final int CASE = 13;
  public static final int NOTEQUAL = 24;
  public static final int LPAREN = 38;
  public static final int SEMI = 34;
  public static final int CONTINUE = 8;
  public static final int LSEQ = 28;
  public static final int FOR = 15;
  public static final int MINUS = 19;
  public static final int RPAREN = 39;
  public static final int AND = 29;
  public static final int LS = 27;
  public static final int OR = 30;
  public static final int BOOL = 46;
  public static final int QMARK = 44;
  public static final int COMMA = 37;
  public static final int INC = 31;
  public static final int DIV = 21;
  public static final int PLUS = 18;
  public static final int ASSIGN = 33;
  public static final int IF = 5;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 23;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int NUMBER = 45;
  public static final int MOD = 22;
  public static final int IDENT = 48;
  public static final int BREAK = 7;
  public static final int VOID = 4;
  public static final int SWITCH = 12;
  public static final int COL = 36;
  public static final int LBRACE = 40;
  public static final int ELSE = 6;
  public static final int ENUM = 14;
  public static final int READ = 10;
  public static final int RBRACE = 41;
  public static final int PROG = 2;
  public static final int DEC = 32;
  public static final int PRINT = 11;
  public static final int LENGTH = 16;
}

